name: Update README with Language Stats

on:
  schedule:
    - cron: '13 16 * * *'  # UTC 기준으로 16:13, 한국 시간(KST)으로 01:13에 실행
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Backup existing README
        run: cp README.md README_backup.md  # 기존 파일 백업
      - name: Remove Old Stats
        run: |
          grep -v "![Top Langs]" README_backup.md > temp.md && mv temp.md README_backup.md  # 기존 언어 통계 삭제
      - name: Update README with Language Stats
        run: |
          echo "## 개발곰의 깃허브 프로필" > README.md  # 새로운 README.md 파일 작성
          echo "" >> README.md  # 빈 줄 삽입
          echo "![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=UantumBear&theme=light&layout=compact&langs_count=13&count_private=true)" >> README.md  # 언어 통계를 링크로 삽입
          echo "" >> README.md  # 빈 줄 삽입
          tail -n +2 README_backup.md >> README.md  # 백업된 내용에서 두 번째 줄부터 덧붙임
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update language stats in README"
          git push
